-- ============================================================
-- NPP BOOKS: Episode audio URLs (full B&N catalog)
-- Auto-generated by scrape-bn-audio.js
-- Matched: 166 episodes
-- ============================================================

-- Breaking Dawn by Stephenie Meyer
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/7s8tb6/NPBR155-TwilightBreakingDawn.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/7s8tb6/NPBR155-TwilightBreakingDawn.mp3"}'::jsonb
WHERE title = 'Breaking Dawn by Stephenie Meyer' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Book Review: Eclipse by Stephenie Meyer
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/avudhs/NPBR154-TwilightEclipse.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/avudhs/NPBR154-TwilightEclipse.mp3"}'::jsonb
WHERE title = 'Book Review: Eclipse by Stephenie Meyer' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Book Review: New Moon by Stephenie Meyer
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/d57xqr/NPBR153-Twilight_New_Moon79q26.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/d57xqr/NPBR153-Twilight_New_Moon79q26.mp3"}'::jsonb
WHERE title = 'Book Review: New Moon by Stephenie Meyer' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Now Playing Book Review: Twilight by Stephenie Meyer
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/zryrdx/NPBR152-Twilight.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/zryrdx/NPBR152-Twilight.mp3"}'::jsonb
WHERE title = 'Now Playing Book Review: Twilight by Stephenie Meyer' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Harry Potter and the Cursed Child, Parts One and Two: The Official Playscript of the Original West End Production
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/ecteib/BN151-HarryPotterandtheCursedChild.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/ecteib/BN151-HarryPotterandtheCursedChild.mp3"}'::jsonb
WHERE title = 'Harry Potter and the Cursed Child, Parts One and Two: The Official Playscript of the Original West End Production' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Harry Potter and the Deathly Hallows
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/j7s63g/BN150-HarryPotterAndTheDeathlyHallows.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/j7s63g/BN150-HarryPotterAndTheDeathlyHallows.mp3"}'::jsonb
WHERE title = 'Harry Potter and the Deathly Hallows' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Harry Potter and The Half-Blood Prince
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/mhfu56/BN149-HarryPotterAndTheHalfBloodPrince.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/mhfu56/BN149-HarryPotterAndTheHalfBloodPrince.mp3"}'::jsonb
WHERE title = 'Harry Potter and The Half-Blood Prince' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Harry Potter and the Order of the Phoenix
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/kmmyid/BN148-HarryPotterandtheOrderofthePhoenix.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/kmmyid/BN148-HarryPotterandtheOrderofthePhoenix.mp3"}'::jsonb
WHERE title = 'Harry Potter and the Order of the Phoenix' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Harry Potter and the Goblet of Fire
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/5q297i/BN147-HarryPotter04-GobletOfFire.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/5q297i/BN147-HarryPotter04-GobletOfFire.mp3"}'::jsonb
WHERE title = 'Harry Potter and the Goblet of Fire' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Harry Potter and the Prisoner of Azkaban
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/n77bhj/BN146-HarryPotter03-PrisonerOfAzkaban.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/n77bhj/BN146-HarryPotter03-PrisonerOfAzkaban.mp3"}'::jsonb
WHERE title = 'Harry Potter and the Prisoner of Azkaban' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Harry Potter and the Chamber of Secrets
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/gt6uxs/BN145-HarryPotter02-ChamberofSecrets.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/gt6uxs/BN145-HarryPotter02-ChamberofSecrets.mp3"}'::jsonb
WHERE title = 'Harry Potter and the Chamber of Secrets' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Harry Potter And The Philosopher’s Stone
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/w6has7/BN144-HarryPotter01-Sorcerer_sStone73qgk.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/w6has7/BN144-HarryPotter01-Sorcerer_sStone73qgk.mp3"}'::jsonb
WHERE title = 'Harry Potter And The Philosopher’s Stone' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Big Trouble in Little China/Escape from New York by Greg Pak, Daniel Bayliss, and Triona Farrell
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/ilkqtd/BN149-BigTroubleEscapeFromNY.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/ilkqtd/BN149-BigTroubleEscapeFromNY.mp3"}'::jsonb
WHERE title = 'Big Trouble in Little China/Escape from New York by Greg Pak, Daniel Bayliss, and Triona Farrell' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Escape from Cleveland Christopher by Sebela and Maxim Simic
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/wop5pv/BN148-EscapeFromCleveland.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/wop5pv/BN148-EscapeFromCleveland.mp3"}'::jsonb
WHERE title = 'Escape from Cleveland Christopher by Sebela and Maxim Simic' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Escape from New York Vol. 3: Escape to New York by Christopher Sebela and Maxim Simic
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/xowall/BN147-EscapeTONewYork.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/xowall/BN147-EscapeTONewYork.mp3"}'::jsonb
WHERE title = 'Escape from New York Vol. 3: Escape to New York by Christopher Sebela and Maxim Simic' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Escape from Siberia by Christopher Sebela, Diego Barreto, Mike Henderson
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/d632tm/BN146-EscapeFromSiberia.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/d632tm/BN146-EscapeFromSiberia.mp3"}'::jsonb
WHERE title = 'Escape from Siberia by Christopher Sebela, Diego Barreto, Mike Henderson' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Escape from Florida by Christopher Sebela, Diego Barreto, Tim Bradstreet
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/uxvaw2/BN145-EscapeFromFlorida.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/uxvaw2/BN145-EscapeFromFlorida.mp3"}'::jsonb
WHERE title = 'Escape from Florida by Christopher Sebela, Diego Barreto, Tim Bradstreet' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Escape from New York by Mike McQuay
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/r3j29u/BN144-EscapeFromNYNovel.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/r3j29u/BN144-EscapeFromNYNovel.mp3"}'::jsonb
WHERE title = 'Escape from New York by Mike McQuay' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- The Godfather by Mario Puzo
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/iyevnk/BN143-Godfather.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/iyevnk/BN143-Godfather.mp3"}'::jsonb
WHERE title = 'The Godfather by Mario Puzo' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Bad Man by Dathan Auerbach
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/mtzz9y/BN143-BadMan.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/mtzz9y/BN143-BadMan.mp3"}'::jsonb
WHERE title = 'Bad Man by Dathan Auerbach' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Twin Peaks: The Final Dossier by Mark Frost
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/sgkest/BN142-TwinPeaksFinalDossier.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/sgkest/BN142-TwinPeaksFinalDossier.mp3"}'::jsonb
WHERE title = 'Twin Peaks: The Final Dossier by Mark Frost' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- The Hellraiser Chronicles Edited by Stephen Jones (and a look at Damnation Games by Phil and Sarah Stokes_
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/4pizjj/BN141-HellraiserChronicles.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/4pizjj/BN141-HellraiserChronicles.mp3"}'::jsonb
WHERE title = 'The Hellraiser Chronicles Edited by Stephen Jones (and a look at Damnation Games by Phil and Sarah Stokes_' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Leviathan: The Story of Hellraiser and Hellbound: Hellraiser II by Christian Sellers and Gary Smart
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/dh2g9x/BN140-Leviathan.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/dh2g9x/BN140-Leviathan.mp3"}'::jsonb
WHERE title = 'Leviathan: The Story of Hellraiser and Hellbound: Hellraiser II by Christian Sellers and Gary Smart' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- The Hellbound Heart by Clive Barker
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/d2etvr/BN139-HellboundHeart.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/d2etvr/BN139-HellboundHeart.mp3"}'::jsonb
WHERE title = 'The Hellbound Heart by Clive Barker' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- The Dark Tower: The Art of the Film by Daniel Wallace
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/gjanvi/BN138-ArtofDarkTower.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/gjanvi/BN138-ArtofDarkTower.mp3"}'::jsonb
WHERE title = 'The Dark Tower: The Art of the Film by Daniel Wallace' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Twin Peaks: The Secret History of Twin Peaks by Mark Frost
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/6w4uzi/BN137-TwinPeaksSecretHistory.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/6w4uzi/BN137-TwinPeaksSecretHistory.mp3"}'::jsonb
WHERE title = 'Twin Peaks: The Secret History of Twin Peaks by Mark Frost' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Catching the Big Fish by David Lynch
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/4pmbae/BN136-DavidLynchBigFish.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/4pmbae/BN136-DavidLynchBigFish.mp3"}'::jsonb
WHERE title = 'Catching the Big Fish by David Lynch' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Welcome to Twin Peaks: Access Guide to the Town
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/x5gqzn/BN135-TwinPeaksAccessGuide.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/x5gqzn/BN135-TwinPeaksAccessGuide.mp3"}'::jsonb
WHERE title = 'Welcome to Twin Peaks: Access Guide to the Town' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Twin Peaks: The Autobiography of FBI Agent Dale Cooper -- My Life, My Tapes by Scott Frost
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/p2dspz/BN134-DaleCooperMyLifeMyTapes.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/p2dspz/BN134-DaleCooperMyLifeMyTapes.mp3"}'::jsonb
WHERE title = 'Twin Peaks: The Autobiography of FBI Agent Dale Cooper -- My Life, My Tapes by Scott Frost' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Twin Peaks: Diane - Twin Peaks Tapes of Agent Cooper by Scott Frost
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/vrtqx5/BN133-TwinPeaks-CooperTapes.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/vrtqx5/BN133-TwinPeaks-CooperTapes.mp3"}'::jsonb
WHERE title = 'Twin Peaks: Diane - Twin Peaks Tapes of Agent Cooper by Scott Frost' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Twin Peaks: The Secret Diary of Laura Palmer by Jennifer Lynch
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/n2fpzx/BN132-TwinPeaks-SecretDiary.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/n2fpzx/BN132-TwinPeaks-SecretDiary.mp3"}'::jsonb
WHERE title = 'Twin Peaks: The Secret Diary of Laura Palmer by Jennifer Lynch' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Children of Dune by Frank Herbert
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/g4rm28/BN131-DuneChildren.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/g4rm28/BN131-DuneChildren.mp3"}'::jsonb
WHERE title = 'Children of Dune by Frank Herbert' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Dune Messiah by Frank Herbert
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/zgys9b/BN130-DuneMessiah.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/zgys9b/BN130-DuneMessiah.mp3"}'::jsonb
WHERE title = 'Dune Messiah by Frank Herbert' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Dune by Frank Herbert
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/4vjy3k/BN129-Dune.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/4vjy3k/BN129-Dune.mp3"}'::jsonb
WHERE title = 'Dune by Frank Herbert' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- The Bourne Ultimatum by Robert Ludlum
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/kkadn7/BN128-BourneUltimatum.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/kkadn7/BN128-BourneUltimatum.mp3"}'::jsonb
WHERE title = 'The Bourne Ultimatum by Robert Ludlum' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- The Bourne Supremacy by Robert Ludlum
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/rq3cvu/BN127-BourneSupremacy.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/rq3cvu/BN127-BourneSupremacy.mp3"}'::jsonb
WHERE title = 'The Bourne Supremacy by Robert Ludlum' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- The Bourne Identity by Robert Ludlum
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/c36fnk/BN126-BourneIdentity.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/c36fnk/BN126-BourneIdentity.mp3"}'::jsonb
WHERE title = 'The Bourne Identity by Robert Ludlum' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Independence Day: Crucible by Greg Keyes
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/p5eu26/BN125-ID4Crucible.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/p5eu26/BN125-ID4Crucible.mp3"}'::jsonb
WHERE title = 'Independence Day: Crucible by Greg Keyes' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- The Dead Zone by Stephen King
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/wmwkey/BN124-SK29-TheDeadZone.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/wmwkey/BN124-SK29-TheDeadZone.mp3"}'::jsonb
WHERE title = 'The Dead Zone by Stephen King' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Watchmen by Alan Moore
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/wmzqfs/BN123-Watchmen.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/wmzqfs/BN123-Watchmen.mp3"}'::jsonb
WHERE title = 'Watchmen by Alan Moore' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Mockingjay by Suzanne Collins
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/963tmc/BN122-HungerGamesMockingjay.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/963tmc/BN122-HungerGamesMockingjay.mp3"}'::jsonb
WHERE title = 'Mockingjay by Suzanne Collins' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Catching Fire by Suzanne Collins
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/3q5hjq/BN121-HungerGamesCatchingFire.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/3q5hjq/BN121-HungerGamesCatchingFire.mp3"}'::jsonb
WHERE title = 'Catching Fire by Suzanne Collins' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- The Hunger Games by Suzanne Collins
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/bs9gt2/BN120-HungerGames.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/bs9gt2/BN120-HungerGames.mp3"}'::jsonb
WHERE title = 'The Hunger Games by Suzanne Collins' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Battle Royale by Koushun Takami
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/rtqvb9/BN119-BattleRoyale.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/rtqvb9/BN119-BattleRoyale.mp3"}'::jsonb
WHERE title = 'Battle Royale by Koushun Takami' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- The Lost World by Michael Crichton
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/rya7sb/BN118-LostWorld.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/rya7sb/BN118-LostWorld.mp3"}'::jsonb
WHERE title = 'The Lost World by Michael Crichton' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Jurassic Park by Michael Crichton
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/mcugez/BN117-JurassicPark.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/mcugez/BN117-JurassicPark.mp3"}'::jsonb
WHERE title = 'Jurassic Park by Michael Crichton' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- The Long Walk by Stephen King (as Richard Bachman)
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/25m4jp/BN116-King28-TheLongWalk.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/25m4jp/BN116-King28-TheLongWalk.mp3"}'::jsonb
WHERE title = 'The Long Walk by Stephen King (as Richard Bachman)' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- The Secret Service:  Kingsman by Mark Millar, Dave Gibbons, and Matthew Vaughn
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/vuizui/BN115-SecretService.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/vuizui/BN115-SecretService.mp3"}'::jsonb
WHERE title = 'The Secret Service:  Kingsman by Mark Millar, Dave Gibbons, and Matthew Vaughn' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- The Stand by Stephen King - Part 6
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/xxnk2v/BN114F-King27-TheStandPartF.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/xxnk2v/BN114F-King27-TheStandPartF.mp3"}'::jsonb
WHERE title = 'The Stand by Stephen King - Part 6' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- The Stand by Stephen King - Part 5
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/ghqfv5/BN114E-King27-TheStandPartE.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/ghqfv5/BN114E-King27-TheStandPartE.mp3"}'::jsonb
WHERE title = 'The Stand by Stephen King - Part 5' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- The Stand by Stephen King - Part 4
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/fsdnhj/BN114D-King27-TheStandPartD.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/fsdnhj/BN114D-King27-TheStandPartD.mp3"}'::jsonb
WHERE title = 'The Stand by Stephen King - Part 4' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- The Stand by Stephen King - Part 3
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/vww9gq/BN114C-King27-TheStandPartC.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/vww9gq/BN114C-King27-TheStandPartC.mp3"}'::jsonb
WHERE title = 'The Stand by Stephen King - Part 3' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- The Stand by Stephen King - Part 2
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/9ipkkj/BN114B-King27-TheStandPartB.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/9ipkkj/BN114B-King27-TheStandPartB.mp3"}'::jsonb
WHERE title = 'The Stand by Stephen King - Part 2' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- The Stand by Stephen King - Part 1
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/fwqvwc/BN114A-King27-TheStandPartA.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/fwqvwc/BN114A-King27-TheStandPartA.mp3"}'::jsonb
WHERE title = 'The Stand by Stephen King - Part 1' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- The Dark Man by Stephen King
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/7ptrjq/BN113-King26-TheDarkMan.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/7ptrjq/BN113-King26-TheDarkMan.mp3"}'::jsonb
WHERE title = 'The Dark Man by Stephen King' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- The Prestige by Christopher Priest
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/58znqu/BN112-ThePrestige.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/58znqu/BN112-ThePrestige.mp3"}'::jsonb
WHERE title = 'The Prestige by Christopher Priest' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- The Man Who Loved Flowers (from the Night Shift collection) by Stephen King
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/xmxz8j/BN111-King25-NightShift-ManWhoLovedFlowers.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/xmxz8j/BN111-King25-NightShift-ManWhoLovedFlowers.mp3"}'::jsonb
WHERE title = 'The Man Who Loved Flowers (from the Night Shift collection) by Stephen King' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- The Last Rung on the Ladder (from the Night Shift collection) by Stephen King
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/6dy5ji/BN110-King24-NightShift-LastRungontheLadder.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/6dy5ji/BN110-King24-NightShift-LastRungontheLadder.mp3"}'::jsonb
WHERE title = 'The Last Rung on the Ladder (from the Night Shift collection) by Stephen King' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- The Lord of the Rings: The Return of the King by J. R. R. Tolkien
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/ytkbs5/BN109-LOTR04-ReturnOfTheKing.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/ytkbs5/BN109-LOTR04-ReturnOfTheKing.mp3"}'::jsonb
WHERE title = 'The Lord of the Rings: The Return of the King by J. R. R. Tolkien' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- The Lord of the Rings: The Two Towers by J. R. R. Tolkien
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/b7q7aj/BN108-LOTR03-2Towers.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/b7q7aj/BN108-LOTR03-2Towers.mp3"}'::jsonb
WHERE title = 'The Lord of the Rings: The Two Towers by J. R. R. Tolkien' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- The Lord of the Rings: The Fellowship of the Ring by J. R. R. Tolkien
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/ayke3k/BN107-LOTR02-Fellowship.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/ayke3k/BN107-LOTR02-Fellowship.mp3"}'::jsonb
WHERE title = 'The Lord of the Rings: The Fellowship of the Ring by J. R. R. Tolkien' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- The Hobbit by J. R. R. Tolkien
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/hmut2h/BN106-LOTR01-Hobbit.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/hmut2h/BN106-LOTR01-Hobbit.mp3"}'::jsonb
WHERE title = 'The Hobbit by J. R. R. Tolkien' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Children of the Corn (from the Night Shift collection) by Stephen King
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/8jcdkn/BN105-King23-NightShift-ChildrenoftheCorn.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/8jcdkn/BN105-King23-NightShift-ChildrenoftheCorn.mp3"}'::jsonb
WHERE title = 'Children of the Corn (from the Night Shift collection) by Stephen King' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Dawn of the Planet of the Apes: Firestorm by Greg Keyes
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/zxvy2a/BN104-DawnofthePlanetoftheApesFirestorm.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/zxvy2a/BN104-DawnofthePlanetoftheApesFirestorm.mp3"}'::jsonb
WHERE title = 'Dawn of the Planet of the Apes: Firestorm by Greg Keyes' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Conspiracy of the Planet of the Apes by Andrew E. C. Gaska
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/wyjsj2/BN103-ConspiracyofPlanetoftheApes.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/wyjsj2/BN103-ConspiracyofPlanetoftheApes.mp3"}'::jsonb
WHERE title = 'Conspiracy of the Planet of the Apes by Andrew E. C. Gaska' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Planet of the Apes: The Fall and Planet of the Apes: Colony by William T. Quick
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/n7s4jz/BN102-PlanetoftheApesFallandColonyByWilliamTQuick.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/n7s4jz/BN102-PlanetoftheApesFallandColonyByWilliamTQuick.mp3"}'::jsonb
WHERE title = 'Planet of the Apes: The Fall and Planet of the Apes: Colony by William T. Quick' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- 3001: The Final Odyssey by Arthur C. Clarke
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/h5fsfr/BN101-3001-ArthurCClarke.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/h5fsfr/BN101-3001-ArthurCClarke.mp3"}'::jsonb
WHERE title = '3001: The Final Odyssey by Arthur C. Clarke' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- 2061: Odyssey Three by Arthur C. Clarke
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/mguzm9/BN100-2061-ArthurCClarke.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/mguzm9/BN100-2061-ArthurCClarke.mp3"}'::jsonb
WHERE title = '2061: Odyssey Three by Arthur C. Clarke' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- 2010: Odyssey Two by Arthur C. Clarke
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/ki9r34/BN099-2010byArthurCClarke.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/ki9r34/BN099-2010byArthurCClarke.mp3"}'::jsonb
WHERE title = '2010: Odyssey Two by Arthur C. Clarke' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- 2001: A Space Odyssey by Arthur C. Clarke
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/3sezsd/BN098-2001byArthurCClarke.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/3sezsd/BN098-2001byArthurCClarke.mp3"}'::jsonb
WHERE title = '2001: A Space Odyssey by Arthur C. Clarke' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Planet of the Apes by Pierre Boulle
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/bctpbj/BN097-PlanetofTheApes.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/bctpbj/BN097-PlanetofTheApes.mp3"}'::jsonb
WHERE title = 'Planet of the Apes by Pierre Boulle' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- I Know What You Need (from the Night Shift collection) by Stephen King
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/swmtd9/BN096-King22-NightShift-IKnowWhatYouNeed.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/swmtd9/BN096-King22-NightShift-IKnowWhatYouNeed.mp3"}'::jsonb
WHERE title = 'I Know What You Need (from the Night Shift collection) by Stephen King' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Lawnmower Man (from the Night Shift collection) by Stephen King
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/fium2h/BN095-King21-NightShift-LawnmowerMan.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/fium2h/BN095-King21-NightShift-LawnmowerMan.mp3"}'::jsonb
WHERE title = 'Lawnmower Man (from the Night Shift collection) by Stephen King' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Strawberry Spring (from the Night Shift collection) by Stephen King
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/8pm96c/BN094-King20-NightShift-StrawberrySpring.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/8pm96c/BN094-King20-NightShift-StrawberrySpring.mp3"}'::jsonb
WHERE title = 'Strawberry Spring (from the Night Shift collection) by Stephen King' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Trucks (from the Night Shift collection) by Stephen King
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/5m3qch/BN093-King19-NightShift-Trucks.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/5m3qch/BN093-King19-NightShift-Trucks.mp3"}'::jsonb
WHERE title = 'Trucks (from the Night Shift collection) by Stephen King' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Battleground (from the Night Shift collection) by Stephen King
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/nd3dqi/BN092-King18-NightShift-Battleground.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/nd3dqi/BN092-King18-NightShift-Battleground.mp3"}'::jsonb
WHERE title = 'Battleground (from the Night Shift collection) by Stephen King' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Sometimes They Come Back (from the Night Shift collection) by Stephen King
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/8vfp9e/BN091-King17-NightShift-SometimesTheyComeBack.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/8vfp9e/BN091-King17-NightShift-SometimesTheyComeBack.mp3"}'::jsonb
WHERE title = 'Sometimes They Come Back (from the Night Shift collection) by Stephen King' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Gray Matter (from the Night Shift collection) by Stephen King
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/9im3n9/BN090-King16-NightShift-GrayMatter.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/9im3n9/BN090-King16-NightShift-GrayMatter.mp3"}'::jsonb
WHERE title = 'Gray Matter (from the Night Shift collection) by Stephen King' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- I Am the Doorway (from the Night Shift collection) by Stephen King
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/kn3t8i/BN089-King15-NightShift-IAmTheDoorway.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/kn3t8i/BN089-King15-NightShift-IAmTheDoorway.mp3"}'::jsonb
WHERE title = 'I Am the Doorway (from the Night Shift collection) by Stephen King' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Night Surf (from the Night Shift collection) by Stephen King
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/7p49mm/BN088-King14-NightShift-NightSurf.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/7p49mm/BN088-King14-NightShift-NightSurf.mp3"}'::jsonb
WHERE title = 'Night Surf (from the Night Shift collection) by Stephen King' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- The Mangler (from the Night Shift collection) by Stephen King
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/j23n98/BN087-King13-NightShift-TheMangler.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/j23n98/BN087-King13-NightShift-TheMangler.mp3"}'::jsonb
WHERE title = 'The Mangler (from the Night Shift collection) by Stephen King' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Graveyard Shift (from the Night Shift collection) by Stephen King
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/rcxc4q/BN086-King12-NightShift-GraveyardShift.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/rcxc4q/BN086-King12-NightShift-GraveyardShift.mp3"}'::jsonb
WHERE title = 'Graveyard Shift (from the Night Shift collection) by Stephen King' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Quitters Inc. (from the Night Shift collection) by Stephen King
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/fthc2a/BN085-King11-NightShift-QuittersInc.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/fthc2a/BN085-King11-NightShift-QuittersInc.mp3"}'::jsonb
WHERE title = 'Quitters Inc. (from the Night Shift collection) by Stephen King' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- The Ledge (from the Night Shift collection) by Stephen King
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/2p4hw8/BN084-King10-NightShift-TheLedge.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/2p4hw8/BN084-King10-NightShift-TheLedge.mp3"}'::jsonb
WHERE title = 'The Ledge (from the Night Shift collection) by Stephen King' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- The Boogeyman (from the Night Shift collection) by Stephen King
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/r9rxvh/BN083-King09-NightShift-TheBoogeyman.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/r9rxvh/BN083-King09-NightShift-TheBoogeyman.mp3"}'::jsonb
WHERE title = 'The Boogeyman (from the Night Shift collection) by Stephen King' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- The Woman in the Room (from the Night Shift collection) by Stephen King
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/q6rmz9/BN082-King08-NightShift-TheWomanintheRoom.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/q6rmz9/BN082-King08-NightShift-TheWomanintheRoom.mp3"}'::jsonb
WHERE title = 'The Woman in the Room (from the Night Shift collection) by Stephen King' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Rage by Stephen King (as Richard Bachman)
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/easu89/BN081-King07-Rage.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/easu89/BN081-King07-Rage.mp3"}'::jsonb
WHERE title = 'Rage by Stephen King (as Richard Bachman)' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- The Wolf of Wall Street and Catching the Wolf of Wall Street by Jordan Belfort
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/5ez3yt/BN079-WolfofWallStreet.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/5ez3yt/BN079-WolfofWallStreet.mp3"}'::jsonb
WHERE title = 'The Wolf of Wall Street and Catching the Wolf of Wall Street by Jordan Belfort' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Doctor Sleep by Stephen King
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/mj3kcz/BN078-King06-DoctorSleep.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/mj3kcz/BN078-King06-DoctorSleep.mp3"}'::jsonb
WHERE title = 'Doctor Sleep by Stephen King' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- The Shining by Stephen King
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/ei9xzt/BN077-King05-TheShining.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/ei9xzt/BN077-King05-TheShining.mp3"}'::jsonb
WHERE title = 'The Shining by Stephen King' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Jersulam's Lot (from the Night Shift Collection) by Stephen King
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/i68nkt/BN076-King04-NightShift-JerusalemsLot.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/i68nkt/BN076-King04-NightShift-JerusalemsLot.mp3"}'::jsonb
WHERE title = 'Jersulam''s Lot (from the Night Shift Collection) by Stephen King' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- One For the Road (from the Night Shift Collection) by Stephen King
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/8e7e3r/BN075-King03-NightShift-OneForTheRoad.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/8e7e3r/BN075-King03-NightShift-OneForTheRoad.mp3"}'::jsonb
WHERE title = 'One For the Road (from the Night Shift Collection) by Stephen King' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- 'Salem's Lot by Stephen King
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/vfi9ts/BN074-King02-SalemsLot.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/vfi9ts/BN074-King02-SalemsLot.mp3"}'::jsonb
WHERE title = '''Salem''s Lot by Stephen King' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Murder and Other Distractions by Michael Estrin
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/fvak5e/BN073-MurderandDistractions.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/fvak5e/BN073-MurderandDistractions.mp3"}'::jsonb
WHERE title = 'Murder and Other Distractions by Michael Estrin' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Dracula by Bram Stoker
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/ihtpu5/BN072-Dracula.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/ihtpu5/BN072-Dracula.mp3"}'::jsonb
WHERE title = 'Dracula by Bram Stoker' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Psycho House by Robert Bloch
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/mixszd/BN071-PsychoHouse.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/mixszd/BN071-PsychoHouse.mp3"}'::jsonb
WHERE title = 'Psycho House by Robert Bloch' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Carrie by Stephen King
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/pbjvhu/BN070-King01-Carrie.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/pbjvhu/BN070-King01-Carrie.mp3"}'::jsonb
WHERE title = 'Carrie by Stephen King' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Psycho II by Robert Bloch
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/x9regj/BN069-Psycho2.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/x9regj/BN069-Psycho2.mp3"}'::jsonb
WHERE title = 'Psycho II by Robert Bloch' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Psycho by Robert Bloch
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/5wncg9/BN068-PSYCHO.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/5wncg9/BN068-PSYCHO.mp3"}'::jsonb
WHERE title = 'Psycho by Robert Bloch' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- World War Z by Max Brooks
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/dkzpe5/BN067-WWZ.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/dkzpe5/BN067-WWZ.mp3"}'::jsonb
WHERE title = 'World War Z by Max Brooks' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Return of the Living Dead by John Russo
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/84rk8q/BN066-ROTLD.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/84rk8q/BN066-ROTLD.mp3"}'::jsonb
WHERE title = 'Return of the Living Dead by John Russo' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- New Avengers: Breakout Prose Novel by Alisa Kwitney
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/ne45ds/BN065-MarvelProseNewAvengersBreakout.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/ne45ds/BN065-MarvelProseNewAvengersBreakout.mp3"}'::jsonb
WHERE title = 'New Avengers: Breakout Prose Novel by Alisa Kwitney' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Astonishing X-Men: Gifted Prose Novel by Peter David
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/vq8a66/BN064-MarvelProseAstonishingXMenGifted.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/vq8a66/BN064-MarvelProseAstonishingXMenGifted.mp3"}'::jsonb
WHERE title = 'Astonishing X-Men: Gifted Prose Novel by Peter David' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- If Chins Could Kill: Confessions of a B Movie Actor by Bruce Campbell
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/izyzx3/BN063-IfChinsCouldKill.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/izyzx3/BN063-IfChinsCouldKill.mp3"}'::jsonb
WHERE title = 'If Chins Could Kill: Confessions of a B Movie Actor by Bruce Campbell' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Marvel's Civil War Prose Novel by Stuart Moore
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/9cac5p/BN062-MarvelProseCivilWar.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/9cac5p/BN062-MarvelProseCivilWar.mp3"}'::jsonb
WHERE title = 'Marvel''s Civil War Prose Novel by Stuart Moore' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Hellblazer:  Dangerous Habits by Garth Ennis
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/svzpnz/BN061-HellBlazer02-DangerousHabits.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/svzpnz/BN061-HellBlazer02-DangerousHabits.mp3"}'::jsonb
WHERE title = 'Hellblazer:  Dangerous Habits by Garth Ennis' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Hellblazer:  Original Sins by Jamie Delano
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/jxe8nx/BN060-HellBlazer01-OriginalSins.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/jxe8nx/BN060-HellBlazer01-OriginalSins.mp3"}'::jsonb
WHERE title = 'Hellblazer:  Original Sins by Jamie Delano' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- 58 Minutes by Walter Wager
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/72q4cy/BN059-DieHard3-58Minutes.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/72q4cy/BN059-DieHard3-58Minutes.mp3"}'::jsonb
WHERE title = '58 Minutes by Walter Wager' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Nothing Lasts Forever by Roderick Thorp
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/wit7nk/BN058-DieHard2-NothingLastsForever.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/wit7nk/BN058-DieHard2-NothingLastsForever.mp3"}'::jsonb
WHERE title = 'Nothing Lasts Forever by Roderick Thorp' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- The Detective by Roderick Thorp
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/sr3ez3/BN057-DieHard1-TheDetective.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/sr3ez3/BN057-DieHard1-TheDetective.mp3"}'::jsonb
WHERE title = 'The Detective by Roderick Thorp' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Octopussy by Ian Fleming
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/sv2im4/BN056-Bond18-Octopussy.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/sv2im4/BN056-Bond18-Octopussy.mp3"}'::jsonb
WHERE title = 'Octopussy by Ian Fleming' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- The Man With the Golden Gun by Ian Fleming
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/sr3355/BN055-Bond17-ManWithGoldenGun.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/sr3355/BN055-Bond17-ManWithGoldenGun.mp3"}'::jsonb
WHERE title = 'The Man With the Golden Gun by Ian Fleming' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- You Only Live Twice by Ian Fleming
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/wftfr4/BN054-Bond16-YouOnlyLiveTwice.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/wftfr4/BN054-Bond16-YouOnlyLiveTwice.mp3"}'::jsonb
WHERE title = 'You Only Live Twice by Ian Fleming' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Property of a Lady and 007 in New York by Ian Fleming
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/6jkqg5/BN053-Bond15-PropertyNewYork.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/6jkqg5/BN053-Bond15-PropertyNewYork.mp3"}'::jsonb
WHERE title = 'Property of a Lady and 007 in New York by Ian Fleming' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- On Her Majesty's Secret Service by Ian Fleming
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/d25eh3/BN052-Bond14-OnHerMajesty.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/d25eh3/BN052-Bond14-OnHerMajesty.mp3"}'::jsonb
WHERE title = 'On Her Majesty''s Secret Service by Ian Fleming' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- The Spy Who Loved Me by Ian Fleming
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/zgfcf6/BN051-Bond13-SpyWhoLovedMe.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/zgfcf6/BN051-Bond13-SpyWhoLovedMe.mp3"}'::jsonb
WHERE title = 'The Spy Who Loved Me by Ian Fleming' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- The Living Daylights by Ian Fleming
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/2hxkw8/BN050-Bond12-LivingDaylights.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/2hxkw8/BN050-Bond12-LivingDaylights.mp3"}'::jsonb
WHERE title = 'The Living Daylights by Ian Fleming' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Thunderball by Ian Fleming
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/syr5pi/BN049-Bond11-Thunderball.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/syr5pi/BN049-Bond11-Thunderball.mp3"}'::jsonb
WHERE title = 'Thunderball by Ian Fleming' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- For Your Eyes Only by Ian Fleming - Part 3
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/fh6x8b/BN048-Bond10-ForYourEyesOnly.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/fh6x8b/BN048-Bond10-ForYourEyesOnly.mp3"}'::jsonb
WHERE title = 'For Your Eyes Only by Ian Fleming - Part 3' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- For Your Eyes Only by Ian Fleming - Part 2
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/9urzaf/BN047-Bond09-RisicoAndView.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/9urzaf/BN047-Bond09-RisicoAndView.mp3"}'::jsonb
WHERE title = 'For Your Eyes Only by Ian Fleming - Part 2' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- For Your Eyes Only by Ian Fleming - Part 1
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/x7swf8/BN046-Bond08-HoldebrandQOS.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/x7swf8/BN046-Bond08-HoldebrandQOS.mp3"}'::jsonb
WHERE title = 'For Your Eyes Only by Ian Fleming - Part 1' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Goldfinger by Ian Fleming
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/qedv4d/BN045-Bond07-Goldfinger.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/qedv4d/BN045-Bond07-Goldfinger.mp3"}'::jsonb
WHERE title = 'Goldfinger by Ian Fleming' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Dr. No by Ian Fleming
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/saqdff/BN044-Bond06-DrNo.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/saqdff/BN044-Bond06-DrNo.mp3"}'::jsonb
WHERE title = 'Dr. No by Ian Fleming' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- From Russia With Love by Ian Fleming
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/cwf4pq/BN043-Bond05-FromRussiaWithLove.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/cwf4pq/BN043-Bond05-FromRussiaWithLove.mp3"}'::jsonb
WHERE title = 'From Russia With Love by Ian Fleming' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Diamonds are Forever by Ian Fleming
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/krqae7/BN042-Bond04-DiamondsAreForever.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/krqae7/BN042-Bond04-DiamondsAreForever.mp3"}'::jsonb
WHERE title = 'Diamonds are Forever by Ian Fleming' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Moonraker by Ian Fleming
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/22w5mm/BN041-Bond03-Moonraker.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/22w5mm/BN041-Bond03-Moonraker.mp3"}'::jsonb
WHERE title = 'Moonraker by Ian Fleming' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Live and Let Die by Ian Fleming
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/kdwaja/BN040-Bond02-LiveAndLetDie.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/kdwaja/BN040-Bond02-LiveAndLetDie.mp3"}'::jsonb
WHERE title = 'Live and Let Die by Ian Fleming' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Casino Royale by Ian Fleming
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/xaenyk/BN039-Bond01-CasinoRoyale.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/xaenyk/BN039-Bond01-CasinoRoyale.mp3"}'::jsonb
WHERE title = 'Casino Royale by Ian Fleming' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Death Dealt the Hand by John E. Bailor
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/27pdt9/BN038.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/27pdt9/BN038.mp3"}'::jsonb
WHERE title = 'Death Dealt the Hand by John E. Bailor' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Batman: The Killing Joke by Alan Moore
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/c4yr56/BN037.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/c4yr56/BN037.mp3"}'::jsonb
WHERE title = 'Batman: The Killing Joke by Alan Moore' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- The War of the Worlds by H.G. Wells
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/ic8ekf/BN036.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/ic8ekf/BN036.mp3"}'::jsonb
WHERE title = 'The War of the Worlds by H.G. Wells' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Batman: Year One by Frank Miller
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/w5ym3x/BN035.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/w5ym3x/BN035.mp3"}'::jsonb
WHERE title = 'Batman: Year One by Frank Miller' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- E.T.: The Book of the Green Planet by William Kotzwinkle
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/ebex22/BN034.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/ebex22/BN034.mp3"}'::jsonb
WHERE title = 'E.T.: The Book of the Green Planet by William Kotzwinkle' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Batman: The Dark Knight Returns by Frank Miller
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/9vn8pf/BN033.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/9vn8pf/BN033.mp3"}'::jsonb
WHERE title = 'Batman: The Dark Knight Returns by Frank Miller' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Aliens: Female War
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/hwyi5t/BN032.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/hwyi5t/BN032.mp3"}'::jsonb
WHERE title = 'Aliens: Female War' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Aliens: Nightmare Asylum by Steve Perry
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/u3iyvp/BN031.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/u3iyvp/BN031.mp3"}'::jsonb
WHERE title = 'Aliens: Nightmare Asylum by Steve Perry' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Aliens: Earth Hive by Steve Perry
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/4ui2xi/BN030.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/4ui2xi/BN030.mp3"}'::jsonb
WHERE title = 'Aliens: Earth Hive by Steve Perry' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- My Incredible Life as the Hulk by Lou Ferrigno
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/rgz5vj/BN029.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/rgz5vj/BN029.mp3"}'::jsonb
WHERE title = 'My Incredible Life as the Hulk by Lou Ferrigno' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Hannibal Rising
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/botja5/BN028.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/botja5/BN028.mp3"}'::jsonb
WHERE title = 'Hannibal Rising' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Hannibal
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/oyywdr/BN027.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/oyywdr/BN027.mp3"}'::jsonb
WHERE title = 'Hannibal' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Who Goes There?
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/5lsqme/BN026.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/5lsqme/BN026.mp3"}'::jsonb
WHERE title = 'Who Goes There?' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Silence of the Lambs
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/lh0s39/BN025.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/lh0s39/BN025.mp3"}'::jsonb
WHERE title = 'Silence of the Lambs' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Red Dragon
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/3fehj1/BN024.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/3fehj1/BN024.mp3"}'::jsonb
WHERE title = 'Red Dragon' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Jaws: The Revenge by Hank Searls
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/na7b5m/BN023.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/na7b5m/BN023.mp3"}'::jsonb
WHERE title = 'Jaws: The Revenge by Hank Searls' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Healers and Hunters (WARS: The Battle of Phobos - Earthers, Part 1 of 3) by Nathan P. Butler
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/9kixxl/BN022.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/9kixxl/BN022.mp3"}'::jsonb
WHERE title = 'Healers and Hunters (WARS: The Battle of Phobos - Earthers, Part 1 of 3) by Nathan P. Butler' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Jaws by Peter Benchley
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/xuq072/BN021.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/xuq072/BN021.mp3"}'::jsonb
WHERE title = 'Jaws by Peter Benchley' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- The Adjustment Team
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/y3wjxw/BN020.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/y3wjxw/BN020.mp3"}'::jsonb
WHERE title = 'The Adjustment Team' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- The Golden Man
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/m2at8b/BN019.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/m2at8b/BN019.mp3"}'::jsonb
WHERE title = 'The Golden Man' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- A Scanner Darkly by Philip K Dick
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/lr4ywl/BN018.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/lr4ywl/BN018.mp3"}'::jsonb
WHERE title = 'A Scanner Darkly by Philip K Dick' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Paycheck by Philip K Dick
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/98h09h/BN017.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/98h09h/BN017.mp3"}'::jsonb
WHERE title = 'Paycheck by Philip K Dick' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Minority Report by Philip K Dick
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/2909m4/BN016.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/2909m4/BN016.mp3"}'::jsonb
WHERE title = 'Minority Report by Philip K Dick' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Impostor by Philip K Dick
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/vwxd9r/BN015.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/vwxd9r/BN015.mp3"}'::jsonb
WHERE title = 'Impostor by Philip K Dick' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Second Variety by Philip K Dick
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/0hw0hs/BN014.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/0hw0hs/BN014.mp3"}'::jsonb
WHERE title = 'Second Variety by Philip K Dick' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- We Can Remember It For You Wholesale by Philip K. Dick
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/otyv9a/BN013.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/otyv9a/BN013.mp3"}'::jsonb
WHERE title = 'We Can Remember It For You Wholesale by Philip K. Dick' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Do Androids Dream of Electric Sheep by Philip K. Dick
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/qpj6dy/BN012.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/qpj6dy/BN012.mp3"}'::jsonb
WHERE title = 'Do Androids Dream of Electric Sheep by Philip K. Dick' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- An Interview with David Morrell
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/7n0l5f/BN011.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/7n0l5f/BN011.mp3"}'::jsonb
WHERE title = 'An Interview with David Morrell' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Rambo 3 by David Morrell
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/uzxeqk/BN010.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/uzxeqk/BN010.mp3"}'::jsonb
WHERE title = 'Rambo 3 by David Morrell' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Rambo - First Blood Part 2 by David Morrell
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/r6l11a/BN009.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/r6l11a/BN009.mp3"}'::jsonb
WHERE title = 'Rambo - First Blood Part 2 by David Morrell' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- First Blood by David Morell
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/a4zy9t/BN008.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/a4zy9t/BN008.mp3"}'::jsonb
WHERE title = 'First Blood by David Morell' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- George Lucas's Blockbusting edited by Alex Ben Block and Lucy Autrey Wilson
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/yzs7ui/BN007.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/yzs7ui/BN007.mp3"}'::jsonb
WHERE title = 'George Lucas''s Blockbusting edited by Alex Ben Block and Lucy Autrey Wilson' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Indiana Jones and the Army of the Dead by Steve Perry
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/9mv6r7/BN005.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/9mv6r7/BN005.mp3"}'::jsonb
WHERE title = 'Indiana Jones and the Army of the Dead by Steve Perry' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- No Doors No Windows by Joe Schreiber
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/yjbir9/BN004.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/yjbir9/BN004.mp3"}'::jsonb
WHERE title = 'No Doors No Windows by Joe Schreiber' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Infected by Scott Sigler
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/30zvaa/BN003.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/30zvaa/BN003.mp3"}'::jsonb
WHERE title = 'Infected by Scott Sigler' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Iron Man:  Femmes Fatales by Robert Greenberger
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/ar16t7/BN002.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/ar16t7/BN002.mp3"}'::jsonb
WHERE title = 'Iron Man:  Femmes Fatales by Robert Greenberger' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- A Walk Through the Book of Matthew Youth Style
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/s2hlxy/BN001.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/s2hlxy/BN001.mp3"}'::jsonb
WHERE title = 'A Walk Through the Book of Matthew Youth Style' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');

-- Under the Dome by Stephen King
UPDATE community_items
SET episode_url = 'https://mcdn.podbean.com/mf/web/bzmpag/BN006.mp3',
    extra_data = COALESCE(extra_data, '{}'::jsonb) || '{"episode_url": "https://mcdn.podbean.com/mf/web/bzmpag/BN006.mp3"}'::jsonb
WHERE title = 'Under the Dome by Stephen King' AND media_type = 'book'
  AND miniseries_id IN (SELECT id FROM community_miniseries WHERE community_id = 'dc0ff496-dce9-4dbf-b56e-5967be6b3b9c' AND tab_key = 'books');
